# Generated by Django 4.0.5 on 2022-07-12 17:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('empId', models.AutoField(primary_key=True, serialize=False)),
                ('empFirstName', models.CharField(max_length=30)),
                ('empLastName', models.CharField(max_length=30)),
                ('empDesignation', models.CharField(max_length=30)),
                ('empSalary', models.FloatField()),
                ('empDoj', models.DateField(default=datetime.datetime.today)),
            ],
        ),
    ]
